server:
  port: 8421
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  mvc:
    view:
      suffix: /
      prefix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/buddhism?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 8421
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 0
mybatis:
  mapper-locations: classpath:com/baizhi/cmm/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.cmm.entity